# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "kontoapi-ruby"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jan Schwenzien"]
  s.date = "2012-04-08"
  s.description = "A ruby library to access the Konto API (https://www.kontoapi.de/), a webservice that performs validity checks and other services regarding german bank accounts."
  s.email = "jan@general-scripting.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "kontoapi-ruby.gemspec",
    "lib/kontoapi-ruby.rb",
    "spec/kontoapi-ruby_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/GeneralScripting/kontoapi-ruby"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Konto API Ruby Library"
  s.test_files = [
    "spec/kontoapi-ruby_spec.rb",
    "spec/spec_helper.rb"
  ]

  
  s.add_runtime_dependency 'addressable'
  s.add_runtime_dependency 'json'
  
  s.add_development_dependency 'bundler'
  s.add_development_dependency 'rake'
  s.add_development_dependency 'rspec'
  s.add_development_dependency 'fakeweb'

end

